export const translations = {
  ar: {
    dir: "rtl",
    siteName: "صانع",
    tagline: "أقرب الحرفيين إليك",
    subTagline: "ابحث عن أفضل الحرفيين في منطقتك بكل سهولة وأمان",
    searchPlaceholder: "ابحث عن خدمة... (سباك، كهربائي...)",
    findNear: "ابحث بالقرب مني",
    enterCity: "أدخل مدينتك",
    radius: "نطاق البحث",
    km: "كم",
    listView: "قائمة",
    mapView: "خريطة",
    allServices: "كل الخدمات",
    services: {
      plumber:     { name: "سباك",       icon: "🔧" },
      electrician: { name: "كهربائي",    icon: "⚡" },
      carpenter:   { name: "نجار",       icon: "🪚" },
      cleaner:     { name: "تنظيف",      icon: "🧹" },
      ac:          { name: "تكييف",      icon: "❄️" },
    },
    away: "كم منك",
    rating: "التقييم",
    reviews: "تقييمات",
    contact: "تواصل",
    viewProfile: "عرض الملف",
    available: "متاح الآن",
    busy: "مشغول",
    login: "تسجيل الدخول",
    signup: "إنشاء حساب",
    logout: "تسجيل الخروج",
    dashboard: "لوحة التحكم",
    workerSignup: "سجّل كحرفي",
    clientSignup: "سجّل كعميل",
    howItWorks: "كيف يعمل؟",
    step1Title: "ابحث عن خدمة",
    step1Desc: "اختر نوع الخدمة التي تحتاجها",
    step2Title: "اعثر على حرفي قريب",
    step2Desc: "نعرض لك أقرب الحرفيين الموثوقين إليك",
    step3Title: "تواصل مباشرة",
    step3Desc: "اتصل بالحرفي واحجز موعدك بسهولة",
    stats1: "حرفي موثوق",
    stats2: "مدينة مغربية",
    stats3: "عميل سعيد",
    footerDesc: "منصة مغربية لربط العملاء بأفضل الحرفيين المحليين الموثوقين",
    rights: "جميع الحقوق محفوظة",
    email: "البريد الإلكتروني",
    password: "كلمة المرور",
    name: "الاسم الكامل",
    phone: "رقم الهاتف",
    city: "المدينة",
    loginBtn: "دخول",
    signupBtn: "إنشاء حساب",
    noAccount: "ليس لديك حساب؟",
    hasAccount: "لديك حساب؟",
    workerOrClient: "هل أنت حرفي أم عميل؟",
    iAmWorker: "أنا حرفي",
    iAmClient: "أنا عميل",
    specialty: "تخصصك",
    experience: "سنوات الخبرة",
    bio: "نبذة عنك",
    myRequests: "طلباتي",
    myProfile: "ملفي الشخصي",
    settings: "الإعدادات",
    noResults: "لا توجد نتائج قريبة منك",
    tryExpand: "حاول توسيع نطاق البحث",
    locationDenied: "الرجاء السماح بالوصول إلى موقعك أو أدخل مدينتك يدوياً",
    searching: "جاري البحث...",
    useMyLocation: "استخدم موقعي",
  },
  fr: {
    dir: "ltr",
    siteName: "Sani3",
    tagline: "Les artisans près de chez vous",
    subTagline: "Trouvez les meilleurs artisans de votre quartier facilement et en toute sécurité",
    searchPlaceholder: "Rechercher un service... (plombier, électricien...)",
    findNear: "Rechercher près de moi",
    enterCity: "Entrez votre ville",
    radius: "Rayon de recherche",
    km: "km",
    listView: "Liste",
    mapView: "Carte",
    allServices: "Tous les services",
    services: {
      plumber:     { name: "Plombier",     icon: "🔧" },
      electrician: { name: "Électricien",  icon: "⚡" },
      carpenter:   { name: "Menuisier",    icon: "🪚" },
      cleaner:     { name: "Nettoyage",    icon: "🧹" },
      ac:          { name: "Climatisation",icon: "❄️" },
    },
    away: "km de vous",
    rating: "Note",
    reviews: "avis",
    contact: "Contacter",
    viewProfile: "Voir profil",
    available: "Disponible",
    busy: "Occupé",
    login: "Connexion",
    signup: "Créer un compte",
    logout: "Déconnexion",
    dashboard: "Tableau de bord",
    workerSignup: "S'inscrire comme artisan",
    clientSignup: "S'inscrire comme client",
    howItWorks: "Comment ça marche ?",
    step1Title: "Cherchez un service",
    step1Desc: "Choisissez le type de service dont vous avez besoin",
    step2Title: "Trouvez un artisan proche",
    step2Desc: "Nous affichons les artisans de confiance les plus proches",
    step3Title: "Contactez directement",
    step3Desc: "Appelez l'artisan et prenez rendez-vous facilement",
    stats1: "Artisans vérifiés",
    stats2: "Villes du Maroc",
    stats3: "Clients satisfaits",
    footerDesc: "Plateforme marocaine pour connecter les clients aux meilleurs artisans locaux de confiance",
    rights: "Tous droits réservés",
    email: "Email",
    password: "Mot de passe",
    name: "Nom complet",
    phone: "Téléphone",
    city: "Ville",
    loginBtn: "Se connecter",
    signupBtn: "Créer un compte",
    noAccount: "Pas encore de compte ?",
    hasAccount: "Déjà un compte ?",
    workerOrClient: "Êtes-vous artisan ou client ?",
    iAmWorker: "Je suis artisan",
    iAmClient: "Je suis client",
    specialty: "Spécialité",
    experience: "Années d'expérience",
    bio: "À propos de vous",
    myRequests: "Mes demandes",
    myProfile: "Mon profil",
    settings: "Paramètres",
    noResults: "Aucun résultat près de vous",
    tryExpand: "Essayez d'élargir le rayon de recherche",
    locationDenied: "Veuillez autoriser l'accès à votre position ou entrez votre ville manuellement",
    searching: "Recherche en cours...",
    useMyLocation: "Utiliser ma position",
  }
};
